### ISSUE TITLE
怎么解决选择过多表和列，上下文超出gpt上限呢？

### ISSUE THREAD

**Issue by ShawshankLin** [alibaba/Chat2DB#100]
![image](https://user-images.githubusercontent.com/16248686/237009902-63dd9d1b-6dc9-4857-a2e3-2f226138262b.png)

**Comment by chenxian01** [comment]
这个是OpenAi接口的限制，输入+输出长度不能超过4000个token，你是输入长度就超了还是输出长度超了？如果是输入长度就超了，那就减少上传的表结构信息，如果是输出结果被截断，可以输入继续，OpenAi会继续输出结果
