### ISSUE TITLE
自定义host被覆盖

### ISSUE THREAD

**Issue by HunnyOvO** [alibaba/Chat2DB#105]
key不会被覆盖
这行代码把host给覆盖了 就算改了yaml也没有作用
![image](https://github.com/alibaba/Chat2DB/assets/129027588/309e3e11-b786-4179-9f26-d23ba87de381)

**Comment by chenxian01** [comment]
针对我们的SQL使用场景，host是固定的，你修改host是什么场景？

**Comment by HunnyOvO** [comment]
> 针对我们的SQL使用场景，host是固定的，你修改host是什么场景？

官方的host 需要代理 才能请求 我这边要使用中转的host 不需要代理 所以需要用自己的host

**Comment by chenxian01** [comment]
已发布，请下载最新版使用

**Comment by HunnyOvO** [comment]
辛苦辛苦
