### ISSUE TITLE
openai的代理和局域网内的数据库连接相冲突

### ISSUE THREAD

**Issue by Morzorz** [alibaba/Chat2DB#128]
国内使用开启代理使用chat2db后，会导致数据库无法连接的情况，即使已经在系统层面对数据库的ip段进行了不走代理的配置

**Comment by chenxian01** [comment]
可以不开全局代理，只在客户端里设置AI的代理，下载最新版试下

**Comment by chenxian01** [comment]
已发布，请下载最新版使用
