### ISSUE TITLE
M1 Pro 修改database不生效

### ISSUE THREAD

**Issue by Aboysky** [alibaba/Chat2DB#141]
通过编辑数据源操作将连接中的数据库由postgres修改为demo后，refresh 连接后仍然是postgres数据库，而不是修改后的demo数据库
<img width="550" alt="image" src="https://github.com/alibaba/Chat2DB/assets/52989177/b0460046-ef42-4f09-beaa-f25f3e5eff56">
<img width="225" alt="image" src="https://github.com/alibaba/Chat2DB/assets/52989177/a277a019-d71a-4086-9d74-b229c2663a47">

**Comment by jipengfei-jpf** [comment]
1.0.5已修复
