### ISSUE TITLE
连接异常

### ISSUE THREAD

**Issue by yuanzhixiang** [alibaba/Chat2DB#145]
相同的数据库连接，数据库 server 是 MySQL，选择 MySQL无法连接，报错后该选项一直处于 loading 中，选择 mariadb 可以连上

报错示意图：

![image](https://github.com/alibaba/Chat2DB/assets/25138766/3703a423-be3c-40f7-bb3b-6b23b4913803)

数据库实例：

![image](https://github.com/alibaba/Chat2DB/assets/25138766/60f11ef8-027e-489e-91da-b70347d49f9f)

**Comment by jipengfei-jpf** [comment]
能看下日志吗

**Comment by jipengfei-jpf** [comment]
1.0.5已修复
