### ISSUE TITLE
使用SSH远程连接ClickHouse失败

### ISSUE THREAD

**Issue by YukiLx** [alibaba/Chat2DB#146]
在Mac端最新的1.0.4版本的Chat2DB软件中设置SSH，并测试SSH显示**成功连接**。（在“SSH”标签页中有一个“**使用SSH**”栏目，不清楚这个栏目填写的是什么内容，翻阅了相关文档也没有类似的介绍）
SSH连通成功之后，在“常规”标签页中尝试连接ClickHouse数据库，使用**默认配置**连接后显示`Connection refused: null`，猜测可能是目前还不支持远程SSH连接
在DataGrip中尝试验证远程连接的连通性，同样地设置好SSH并测试连通后，仍然使用软件的默认配置即可顺利连接，但类似的操作在Chat2DB中却显示`Connection refused: null`。

**Comment by jipengfei-jpf** [comment]
使用SSH选择true才表示使用ssh
