### ISSUE TITLE
连接Oracle一直转圈呢

### ISSUE THREAD

**Issue by realtanwei** [alibaba/Chat2DB#147]
![image](https://github.com/alibaba/Chat2DB/assets/17842104/fd28d5b2-4ee8-4233-9e31-e4c683497261)

连接一个本地的Oracle数据库，测试连接信息已成功，但是打开的时候就一直转圈

**Comment by jipengfei-jpf** [comment]
是Windows系统吗

**Comment by jipengfei-jpf** [comment]
1.0.5中已修复
