### ISSUE TITLE
mac client 'COMMON_SYSTEM_ERROR: 系统开小差啦，请尝试刷新页面或者联系管理员'

### ISSUE THREAD

**Issue by DongJigong** [alibaba/Chat2DB#172]
After install the mac dmg, I create a local connect,but I find I cannot open the connection detail, and after a few seconds, the tool popup an error 'COMMON_SYSTEM_ERROR: 系统开小差啦，请尝试刷新页面或者联系管理员'

**Comment by unclay** [comment]
刚试了最新版，1.0.5的。这个问题修复了。
上周都想放弃，第一次使用，连数据库都连接不上去

**Comment by DongJigong** [comment]
It was resolved on version 1.0.5

**Comment by DongJigong** [comment]
After a few moment, I open another mysql datasource connection, It happens again!!!
