### ISSUE TITLE
建议有一个设置openai.api_base的地方

### ISSUE THREAD

**Issue by gaboolic** [alibaba/Chat2DB#173]
现在貌似只能设置代理，本地开代理还是不太稳

**Comment by gaboolic** [comment]
这样服务器反代就能用了

**Comment by gaboolic** [comment]
对应到本项目的修改点是OpenAIClient类
OPEN_AI_STREAM_CLIENT = OpenAiStreamClient.builder().apiHost(OpenAIConst.OPENAI_HOST).apiKey(
                Lists.newArrayList(apikey)).build();

**Comment by baiyutang** [comment]
同意

**Comment by chenxian01** [comment]
已支持，请下载最新版

**Comment by gaboolic** [comment]
> 已支持，请下载最新版

不满足需求。。。
怎么搞成了2个tab，openai的配置没有改变，多了一个自定义tab，自定义tab还只能填url……

反代是搞了一个自己的url，其他所有东西和openai一模一样
对应Openai的库，只需要改openai.api_base啊
api_base = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")

**Comment by gaboolic** [comment]
<img width="795" alt="image" src="https://github.com/alibaba/Chat2DB/assets/3831173/6ac0c08d-73e0-4f2e-8ead-381ed703ece2">

**Comment by gaboolic** [comment]
请参考下chrome浏览器插件openai translater，以及chatall等项目的设置
