### ISSUE TITLE
getJDBCDriver error: null

### ISSUE THREAD

**Issue by tiantsing** [alibaba/Chat2DB#174]
getJDBCDriver error: null
![d62ed88c371ec4d3c6da0b4bd23b8084](https://github.com/alibaba/Chat2DB/assets/19945810/e6dbf4e5-14bd-42a5-b111-80f561ceb91c)

**Comment by cjie** [comment]
+1

**Comment by sendylian** [comment]
是不是没网络啊 我在有网的电脑上连接没这个报错  在公司内网上就报错

**Comment by jipengfei-jpf** [comment]
第一次启动需要联网下载jar包。如何无法联网需要自己手动下载jar包

**Comment by Leo00001** [comment]
+1

**Comment by Leo00001** [comment]
> 
热点联网随便配置测试链接就会自动下载，下载后你在切回内网

**Comment by hlxkurapika** [comment]
公司内网也不是想连热点就连热点啊 XD

**Comment by jipengfei-jpf** [comment]
解决办法：手动下载相关驱动放入到 ~/.chat2db/jdbc-lib 目录下

下载链接 参考：<a href="https://github.com/alibaba/Chat2DB/blob/main/ali-dbhub-server/ali-dbhub-server-start/src/main/resources/application.yml">Application jdbc-jar-downLoad-urls</a> 
- https://oss-chat2db.alibaba.com/lib/mysql-connector-java-8.0.30.jar
- https://oss-chat2db.alibaba.com/lib/mysql-connector-java-5.1.47.jar
- https://oss-chat2db.alibaba.com/lib/clickhouse-jdbc-0.3.2-patch8-http.jar
- https://oss-chat2db.alibaba.com/lib/mariadb-java-client-3.0.8.jar
- https://oss-chat2db.alibaba.com/lib/mssql-jdbc-11.2.1.jre17.jar
- https://oss-chat2db.alibaba.com/lib/oceanbase-client-2.4.2.jar
- https://oss-chat2db.alibaba.com/lib/postgresql-42.5.1.jar
- https://oss-chat2db.alibaba.com/lib/sqlite-jdbc-3.39.3.0.jar
- https://oss-chat2db.alibaba.com/lib/ojdbc11.jar

**Comment by Felix-god** [comment]
+1

**Comment by Felix-god** [comment]
解决了吗？这个应该怎么解决呢？

**Comment by GHleon** [comment]
解决了吗？jar下载了好像也不行
