### ISSUE TITLE
1.0.4版本Windows：自然语言转SQL功能正常，使用SQL解释功能报错。（偶尔出现）

### ISSUE THREAD

**Issue by NingNing0111** [alibaba/Chat2DB#209]
![](https://cdn.staticaly.com/gh/NingNing0111/picx-images-hosting@master/issue/8e22b4f544b1eea3fb4820a4e00ac4bb.26vmbj2og4nw.png)

**Comment by jipengfei-jpf** [comment]
具体报错可以看到吗
