### ISSUE TITLE
Bug: 公布的钉钉号是错误的搜不到

### ISSUE THREAD

**Issue by ccpwcn** [alibaba/Chat2DB#226]
### Chat2DB Version

latest

### Describe the bug

文档中公布的钉钉号，试了好几次，搜不到什么东西，好像是错误的。
既然能发微信二维码，不如同时发一个钉钉群的二维码。

**Comment by tmlx1990** [comment]
钉钉在搜索的地方输入，然后选群组应该是可以搜到的。点一下下图红色位置，应该就能找到了。
![image](https://github.com/alibaba/Chat2DB/assets/5753992/361c2cfa-010f-48a8-b906-49f4359a116d)

**Comment by ccpwcn** [comment]
![Screenshot_20230526_174938_com alibaba android rimet](https://github.com/alibaba/Chat2DB/assets/5465756/1633d70b-ee15-4a96-88c1-1e3b8d215a01)

**Comment by ccpwcn** [comment]
在这里备注一下：
在手机钉钉右上角点＋，然后点添加好友，再搜，是搜不到的。

在手机钉钉的首页，直接在顶部的搜索框中搜，然后选择公开群组，就可以搜到了。

好吧，这不是Chat2DB的问题，是钉钉的使用习惯和微信不同造成的。忽略吧。
