### ISSUE TITLE
优化: 格式化后想撤销却无法撤销，建议格式化后也能撤销吧

### ISSUE THREAD

**Issue by fenfpengfei** [alibaba/Chat2DB#251]

**Comment by shanhexi** [comment]
已修复，会在1.0.8发布

**Comment by fenfpengfei** [comment]
厉害，已经使用起来了，挺好用的
----- 原始邮件 -----
发件人：贺喜 ***@***.***>
收件人：alibaba/Chat2DB ***@***.***>
抄送人：fenfpengfei ***@***.***>,  Author ***@***.***>
主题：Re:_[alibaba/Chat2DB]_优化:_格式化后想撤销却无法撤销，建议格式化后也能撤销吧_(Issue_#251)
日期：2023年05月31日 18点41分


已修复，会在1.0.8发布
