### ISSUE TITLE
优化: SqlServer不支持TLS10

### ISSUE THREAD

**Issue by albertfengjiajun** [alibaba/Chat2DB#252]
报错提示：The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]: null
![image](https://github.com/alibaba/Chat2DB/assets/55448106/2200b268-25ae-4f0c-ba5e-b35603a7bd7b)

**Comment by jipengfei-jpf** [comment]
1.0.9修复

**Comment by kuikuijiademao** [comment]
我下载的1.0.11版本连接sqlserver还是会报这个错

**Comment by klibing** [comment]
我的v1.0.11也出现同样的问题
![image](https://github.com/alibaba/Chat2DB/assets/13029654/e33d0d9f-df30-4a7c-a819-9d677cd9727b)

**Comment by YujiaCheng1996** [comment]
还是报错。。。

**Comment by TangJinJian** [comment]
1.0.11，仍然报错

**Comment by qq8618** [comment]
@jipengfei-jpf  你好  0.11还是有这个问题

**Comment by LSL1618** [comment]
最新版1.0.11还是有这个问题，这修复了个寂寞啊！

**Comment by albertfengjiajun** [comment]
通过修改安装包的java.security文件解决
windows：Chat2DB\resources\app\jre\conf\security
![image](https://github.com/alibaba/Chat2DB/assets/55448106/4cb003f3-4c73-4713-a140-412ecd47e4f5)

**Comment by LSL1618** [comment]
> 通过修改安装包的java.security文件解决 windows：Chat2DB\resources\app\jre\conf\security ![image](https://user-images.githubusercontent.com/55448106/247488678-4cb003f3-4c73-4713-a140-412ecd47e4f5.png)

原来chat2db用的jre是它自带的，难怪我改的没用。

**Comment by kuikuijiademao** [comment]
应该怎么修改这个java.security文件呢

**Comment by almightyYantao** [comment]
修改`resources\app\jre\conf\security`的就可以了，然后重启应用，不重启也无效

**Comment by almightyYantao** [comment]
但是我又出现了新的问题
![image](https://github.com/alibaba/Chat2DB/assets/34707560/d312d65f-5861-4b45-b4ad-eef9477864c8)

**Comment by LSL1618** [comment]
> 应该怎么修改这个java.security文件呢

我前面给的链接里有教程，注意别改错文件了，改JDK安装目录里的没用，要改chat2db安装目录里的才有用。

**Comment by juukee** [comment]
> 1.0.9修复

v1.0.11仍然存在这个问题
