### ISSUE TITLE
Bug: 格式化SQL，结果会追加到编辑器里面了

### ISSUE THREAD

**Issue by wseven10** [alibaba/Chat2DB#266]
### Chat2DB Version

1.0.8

### Describe the bug

<img width="1035" alt="image" src="https://github.com/alibaba/Chat2DB/assets/25626520/e9f0c010-136f-41ad-aba1-a746a148d7de">

**Comment by shanhexi** [comment]
fixed: 格式化SQL异常 versions：1.0.10
