### ISSUE TITLE
Bug: 不等于写成<>时，解释sql会报错

### ISSUE THREAD

**Issue by ZimaBlueee** [alibaba/Chat2DB#291]
### Chat2DB Version

1.0.10

### Describe the bug

sql条件：**不等于用<>写**，**且where条件换行时**，会无法解释sql
`SELECT * FROM user 
WHERE user_id <> 1`

![image](https://github.com/alibaba/Chat2DB/assets/53747502/0a902343-8985-4444-a5ce-ab762934083a)

控制台报错：
![image](https://github.com/alibaba/Chat2DB/assets/53747502/5fb8daa7-cd44-4258-8338-a3b33890a99f)

`<>`换成`!=`，或者sql写成**一行**时，就能正常把请求发到后端

顺便问下前端怎么调试，本来我想自己改bug提pr的，可惜前端的调试怎么都起不来。（本地已经起好环境）

**Comment by shanhexi** [comment]
# 1.0.11
* fixed: SQL有特殊字符时AI功能无法正常使用问题
