### ISSUE TITLE
Bug: 当我使用第三方API接口时，报错了，请问APIKey有限制格式吗？我应该怎样配置才可以使用？

### ISSUE THREAD

**Issue by woodchen-ink** [alibaba/Chat2DB#328]
### Chat2DB Version

latest

## 当我使用JWT格式的密钥，使用第三方接口配置时，openai报错
**密钥例子**：`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNZW1iZXJJZCI6MTMwNjI3OTI3OTMwMjksIkFjY291bnQiOiIxNTIyMTY1NzUxNSIsIkFj*******Y291bnRUeX******NrTmFtZSI6Indvb2RAY3psLm5ldCIsIkxvZ2luTW9kZSI6MiwiaWF0IjoxNjg2NjQyMDY1LCJuYmYiOjE2ODY2NDIwNjUsImV4cCI6MTY4OTIzNDA2NSwiaXNzIjoiQ1pMQUlDaGF0IiwiYXVkIjoiQ1pMQUlDaGF0In0.cZqLf6qMi6WGIdP_Fhq0`
**接口**：`https://czlchat-api.czl.net/v1/chat/completions`
![image](https://github.com/alibaba/Chat2DB/assets/95951386/cb38db36-be4c-4012-b2db-f9eded7f3bf4)
## 接口文档
![image](https://github.com/alibaba/Chat2DB/assets/95951386/1fbe2974-f971-44ba-ba31-c6ff853d43ab)

**Comment by chenxian01** [comment]
怎么配置的，截个图

**Comment by woodchen-ink** [comment]
> 
您好，这样配置的，我感觉可能是因为JWT中有`.`？
![image](https://github.com/alibaba/Chat2DB/assets/95951386/3109fb02-25e8-47b5-aa62-1839e2d9f3bc)

**Comment by woodchen-ink** [comment]
不需要了，我重新搭建了oapi，规定了key的格式和openai相同，可以正常使用了
