### ISSUE TITLE
Bug: License和Readme描述不匹配

### ISSUE THREAD

**Issue by randxie** [alibaba/Chat2DB#377]
### Chat2DB Version

every version

### Describe the bug

这个项目采用了Apache 2.0 license文件, 理应是允许商业使用(commercial use). 但和README.md里面的这段话有冲突"License Notation: Chat2DB is constructed and distributed for personal and non-commercial use only. For commercial use of this project, please contact corresponding authors."

建议澄清一下, either (1) 更换license, or (2) 移除README里面有冲突的段落.

**Comment by jipengfei-jpf** [comment]
谢谢提醒，我更新license
