### ISSUE TITLE
Bug: oracle无法使用sys账号登录

### ISSUE THREAD

**Issue by 2273267033zzz** [alibaba/Chat2DB#421]
### Chat2DB Version

1.0.11

### Describe the bug

<img width="1095" alt="image" src="https://github.com/alibaba/Chat2DB/assets/50507638/7e8c3943-acf6-47fc-ad6d-83713cf1f0ea">

电脑为 m1 max

**Comment by 2273267033zzz** [comment]
<img width="678" alt="image" src="https://github.com/alibaba/Chat2DB/assets/50507638/ed2916c7-f7e2-4d02-a4ba-73a8a5d856b5">

**Comment by jipengfei-jpf** [comment]
高级中 增加：internal_logon=sysdba

**Comment by 2273267033zzz** [comment]
> 高级中 增加：internal_logon=sysdba

谢谢
