### ISSUE TITLE
M1芯片 13寸PRO，安装Chat2DB-1.0.0-arm64.dmg，在测试链接时，报错CLIENT_PLUGIN_AUTH is required: null

### ISSUE THREAD

**Issue by L-Lawliets** [alibaba/Chat2DB#81]
![image](https://user-images.githubusercontent.com/50453073/236388102-6848ae4c-8880-4bea-b8e2-12ed449af79c.png)

**Comment by jipengfei-jpf** [comment]
你的数据库版本是多少？

**Comment by L-Lawliets** [comment]
> 看一下用户目录~.chat2db/logs下的日志

没有找到改目录

**Comment by L-Lawliets** [comment]
> 你的数据库版本是多少？
8.0.22

**Comment by jipengfei-jpf** [comment]
像这样jdbc:mysql://localhost:3306/mydb?useLegacyAuth=true
mysql连接参数后增加 useLegacyAuth=true  试试看呢？

**Comment by L-Lawliets** [comment]
> 像这样jdbc:mysql://localhost:3306/mydb?useLegacyAuth=true mysql连接参数后增加 useLegacyAuth=true 试试看呢？
还是一样，T.T

**Comment by L-Lawliets** [comment]
![image](https://user-images.githubusercontent.com/50453073/236409841-9fbd498b-35e3-4509-9910-1468744738ef.png)
这个数据库使用DataGrip要选这个driver，不知道是不是这个影响

**Comment by jipengfei-jpf** [comment]
嗯嗯，那确实是driver的问题，你的数据库版本应该5.1以下吧，不是8.0.22

**Comment by L-Lawliets** [comment]
> 嗯嗯，那确实是driver的问题，你的数据库版本应该5.1以下吧，不是8.0.22

那啥时候能兼容5.1的

**Comment by jipengfei-jpf** [comment]
加一下这个参数试一下呢？&defaultAuthenticationPlugin=mysql_native_password

**Comment by L-Lawliets** [comment]
> 加一下这个参数试一下呢？&defaultAuthenticationPlugin=mysql_native_password

好像没有作用

**Comment by jipengfei-jpf** [comment]
我把包冲突这个问题提高一些优先级吧，预计下个版本解决

**Comment by L-Lawliets** [comment]
> 我把包冲突这个问题提高一些优先级吧，预计下个版本解决

期待~

**Comment by jipengfei-jpf** [comment]
1.0.3版本已支持
