### ISSUE TITLE
Windows下载版本使用key连接不上chatgpt

### ISSUE THREAD

**Issue by BeyondTheBlade** [alibaba/Chat2DB#82]
rt

**Comment by includewins0ck2** [comment]
俺也一样

**Comment by jipengfei-jpf** [comment]
方便钉钉吗？看一下问题

**Comment by 1033925480** [comment]
自然语言和chatgpt都不能用  该设置的都设置了

**Comment by BeyondTheBlade** [comment]
> 方便钉钉吗？看一下问题

怎么发你

**Comment by lovexiaodong** [comment]
确实连不上，怎么回事呢

**Comment by chenxian01** [comment]
全局代理在应用中未生效的问题，会在客户端中支持代理设置，正在开发测试中

**Comment by lidedongsn** [comment]
同样的问题

**Comment by clong365** [comment]
![微信截图_20230516145247](https://github.com/alibaba/Chat2DB/assets/150419/424f93f0-b5aa-4490-b04d-44a2ab9b3c89)

V2ray开启Tun模式就可以了。

**Comment by chenxian01** [comment]
可以在客户端中设置VPN代理，已发布
