### ISSUE TITLE
gpt请求地址后续是否能支持自定义修改

### ISSUE THREAD

**Issue by zjy18148575040** [alibaba/Chat2DB#83]
gpt请求地址后续是否能支持自定义修改

**Comment by M1sury** [comment]
api-host在后端项目的配置文件中可以换，只是现在需要自己构建

**Comment by M1sury** [comment]
![image](https://user-images.githubusercontent.com/64764195/236652995-79e7570e-4be9-4791-be5d-e2fb99d87607.png)

**Comment by zjy18148575040** [comment]
是的，我上次看代码是这样的，不过在refresh的时候又把它写死了

**Comment by zjy18148575040** [comment]
> ![image](https://user-images.githubusercontent.com/64764195/236652995-79e7570e-4be9-4791-be5d-e2fb99d87607.png)

是的，我上次看代码是这样的，不过在refresh的时候又把它写死了

**Comment by chenxian01** [comment]
已发布，请下载最新版使用
