### ISSUE TITLE
拆分 windows 安装包为 32 位和 64 位

### ISSUE THREAD

**Issue by Vixb1122** [alibaba/Chat2DB#87]
整合的安装包太大了，希望拆分成 32 位和 64 位两个安装包，
类似 MQTTX 的分包方式
![image](https://user-images.githubusercontent.com/17810492/236667408-e5ced39a-6770-49a0-aa59-c44e3a174467.png)
![image](https://user-images.githubusercontent.com/17810492/236667437-ed2d8e74-fbd0-49ed-89f3-45426661d3ce.png)

**Comment by fanjinyu-fjy** [comment]
暂时后端服务不支持32位，windows安装包已剔除32位客户端。
后期会逐步迭代支持。
