### ISSUE TITLE
没有openai的key也可以使用该产品吗？

### ISSUE THREAD

**Issue by longcz666** [alibaba/Chat2DB#92]
没有openai的key也可以使用该产品吗？选中语句后点击自然语言转sql按钮没反应是怎么回事？

**Comment by jipengfei-jpf** [comment]
可以的，但是AI的功能就没办法使用

**Comment by longcz666** [comment]
![image](https://user-images.githubusercontent.com/105555938/236725508-39bbdeb6-37fb-407d-a61c-9770909f9ad8.png)
配了key点自然语言转sql还是没反应是怎么回事？

**Comment by tmlx1990** [comment]
> ![image](https://user-images.githubusercontent.com/105555938/236725508-39bbdeb6-37fb-407d-a61c-9770909f9ad8.png) 配了key点自然语言转sql还是没反应是怎么回事？

后台服务地址默认就行。尝试下用浏览器访问这个后台地址，看看chatRobot有返回吗？

**Comment by chenxian01** [comment]
全局代理在应用中未生效的问题，会在客户端中支持代理设置，正在开发中

**Comment by ZhangTianWei94** [comment]
在应用外部使用clash of windows 挂载美国节点 的情况下：更新openai api key 成功，访问默认后台服务地址http://127.0.0.1:10824成功唤醒chat2DB网页版界面，但chatRobot和自然语言转sql等功能依旧无法使用，应是全局代理未生效的缘故。

**Comment by dq7532183** [comment]
需要使用代理才能用openai的aigc
阿里不是自己有通义千问么

**Comment by HildaM** [comment]
支持claude、poe.com等免费GPT接口吗？或者说支持国内星火大模型、阿里、百度等这些吗？还有能支持本地模型吗？

**Comment by tmlx1990** [comment]
> 使用代理才能用openai的aigc

阿里的目前还没有开放，所以只能先接入chatgpt

**Comment by chenxian01** [comment]
可以在客户端中设置VPN代理，已发布
