### ISSUE TITLE
docker 部署是认真的吗?tag都没有咋下载镜像

### ISSUE THREAD

**Issue by zhuleiandy888** [alibaba/Chat2DB#95]

**Comment by zhuleiandy888** [comment]
![image](https://user-images.githubusercontent.com/13164631/236785139-44f73561-d5c0-4b70-83cd-c1665226e143.png)

**Comment by zhuangjiaju** [comment]
请尝试检查下 是否使用了中文的斜杠之类的。
或者直接复制如下命令，实测没有问题。
```cmd
docker pull chat2db/chat2db:latest
```
![image](https://user-images.githubusercontent.com/18475586/236816294-6d102dc3-0a44-448e-a11b-9fd794972401.png)
